### ISSUE TITLE
Support/Changes for v5.1.1.3

### ISSUE THREAD

**Issue by slauger** [IBM/ibm-spectrum-scale-container-native-helm#2]
It seems that v5.1.1.3 introduces a lot of changes in the custom resource definitions.

Will we see and update for v5.1.1.3 or can this chart be used for the new version?

https://www.ibm.com/docs/en/scalecontainernative?topic=overview-whats-new

Thank you.

**Comment by gfschmidt** [comment]
Unfortunately, the 5.1.1.1 chart cannot be used for the 5.1.1.3 version. There are significant changes that were applied to 5.1.1.3 with a combined deployment of IBM Spectrum Scale CNSA and IBM Spectrum Scale CSI. Clients already running CNSA 5.1.1.1 need to follow the official documentation for the upgrade procedure [here](https://www.ibm.com/docs/en/scalecontainernative?topic=5113-upgrade-spectrum-scale-container-native).  I will look into the effort of updating the Helm charts.

**Comment by gfschmidt** [comment]
Update: Instead of working on CNSA 5.1.1.3 I was waiting for the release of CNSA 5.1.1.4 with CSI 2.3.1 and am now finalizing a release of a single Helm chart for it. As the resources for CNSA 5.1.1.4 have changed considerably compared to CNSA 5.1.1.1 the Helm chart will be a completely new one. It will be released soon.

**Comment by slauger** [comment]
Since we were forced by the storage team to upgrade to 5.1.1.4, we already created a custom chart for us, which only contains the new CR objects.

For the installation of the operator / CRDs i would prefer the OLM (Operator Lifecycle Manager) instead of an helm chart. This would simplify the lifecycle/update management of the operator even more.

**Comment by gfschmidt** [comment]
Closing this issue with the release of a new Helm chart for CNSA 5.1.1.4.
